# Generated by Django 5.1.3 on 2024-11-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
