# Generated by Django 5.1.3 on 2024-11-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_type_alter_docs_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='photo',
            field=models.ImageField(default=2, upload_to='docs/'),
            preserve_default=False,
        ),
    ]
