# Generated by Django 5.1.3 on 2025-01-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_docs_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docs',
            old_name='type',
            new_name='tipe',
        ),
        migrations.AlterField(
            model_name='docs',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='docs/'),
        ),
    ]
