# Generated by Django 5.1.3 on 2025-01-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_alter_docs_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
