# Generated by Django 5.1.3 on 2025-01-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_docs_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='docs/'),
        ),
    ]
